// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reg.proto

#ifndef PROTOBUF_reg_2eproto__INCLUDED
#define PROTOBUF_reg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace MSG {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_reg_2eproto();
void protobuf_AssignDesc_reg_2eproto();
void protobuf_ShutdownFile_reg_2eproto();

class reg;

// ===================================================================

class reg : public ::google::protobuf::Message {
 public:
  reg();
  virtual ~reg();

  reg(const reg& from);

  inline reg& operator=(const reg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const reg& default_instance();

  void Swap(reg* other);

  // implements Message ----------------------------------------------

  reg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const reg& from);
  void MergeFrom(const reg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 career = 1;
  inline bool has_career() const;
  inline void clear_career();
  static const int kCareerFieldNumber = 1;
  inline ::google::protobuf::int32 career() const;
  inline void set_career(::google::protobuf::int32 value);

  // required int32 sex = 2;
  inline bool has_sex() const;
  inline void clear_sex();
  static const int kSexFieldNumber = 2;
  inline ::google::protobuf::int32 sex() const;
  inline void set_sex(::google::protobuf::int32 value);

  // required string account = 3;
  inline bool has_account() const;
  inline void clear_account();
  static const int kAccountFieldNumber = 3;
  inline const ::std::string& account() const;
  inline void set_account(const ::std::string& value);
  inline void set_account(const char* value);
  inline void set_account(const char* value, size_t size);
  inline ::std::string* mutable_account();
  inline ::std::string* release_account();
  inline void set_allocated_account(::std::string* account);

  // @@protoc_insertion_point(class_scope:MSG.reg)
 private:
  inline void set_has_career();
  inline void clear_has_career();
  inline void set_has_sex();
  inline void clear_has_sex();
  inline void set_has_account();
  inline void clear_has_account();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 career_;
  ::google::protobuf::int32 sex_;
  ::std::string* account_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_reg_2eproto();
  friend void protobuf_AssignDesc_reg_2eproto();
  friend void protobuf_ShutdownFile_reg_2eproto();

  void InitAsDefaultInstance();
  static reg* default_instance_;
};
// ===================================================================


// ===================================================================

// reg

// required int32 career = 1;
inline bool reg::has_career() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void reg::set_has_career() {
  _has_bits_[0] |= 0x00000001u;
}
inline void reg::clear_has_career() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void reg::clear_career() {
  career_ = 0;
  clear_has_career();
}
inline ::google::protobuf::int32 reg::career() const {
  return career_;
}
inline void reg::set_career(::google::protobuf::int32 value) {
  set_has_career();
  career_ = value;
}

// required int32 sex = 2;
inline bool reg::has_sex() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void reg::set_has_sex() {
  _has_bits_[0] |= 0x00000002u;
}
inline void reg::clear_has_sex() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void reg::clear_sex() {
  sex_ = 0;
  clear_has_sex();
}
inline ::google::protobuf::int32 reg::sex() const {
  return sex_;
}
inline void reg::set_sex(::google::protobuf::int32 value) {
  set_has_sex();
  sex_ = value;
}

// required string account = 3;
inline bool reg::has_account() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void reg::set_has_account() {
  _has_bits_[0] |= 0x00000004u;
}
inline void reg::clear_has_account() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void reg::clear_account() {
  if (account_ != &::google::protobuf::internal::kEmptyString) {
    account_->clear();
  }
  clear_has_account();
}
inline const ::std::string& reg::account() const {
  return *account_;
}
inline void reg::set_account(const ::std::string& value) {
  set_has_account();
  if (account_ == &::google::protobuf::internal::kEmptyString) {
    account_ = new ::std::string;
  }
  account_->assign(value);
}
inline void reg::set_account(const char* value) {
  set_has_account();
  if (account_ == &::google::protobuf::internal::kEmptyString) {
    account_ = new ::std::string;
  }
  account_->assign(value);
}
inline void reg::set_account(const char* value, size_t size) {
  set_has_account();
  if (account_ == &::google::protobuf::internal::kEmptyString) {
    account_ = new ::std::string;
  }
  account_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* reg::mutable_account() {
  set_has_account();
  if (account_ == &::google::protobuf::internal::kEmptyString) {
    account_ = new ::std::string;
  }
  return account_;
}
inline ::std::string* reg::release_account() {
  clear_has_account();
  if (account_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = account_;
    account_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void reg::set_allocated_account(::std::string* account) {
  if (account_ != &::google::protobuf::internal::kEmptyString) {
    delete account_;
  }
  if (account) {
    set_has_account();
    account_ = account;
  } else {
    clear_has_account();
    account_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace MSG

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_reg_2eproto__INCLUDED
